import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const sourceSansPro = Source_Sans_3({
  subsets: ["latin"],
  variable: "--font-sourceSansPro",
});

const pretendard = localFont({
  src: "../font/PretendardVariable.woff2",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.className} ${sourceSansPro.className} bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
