name: Comment Triggered Workflow

on:
  issue_comment:
    types:
      - created

jobs:
  comment-triggered-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check Comment for "리뷰중"
        id: check-comment
        run: |
          body=$(echo "${{ github.event.comment.body }}" | tr '[:upper:]' '[:lower:]')
          if [[ $body == *"리뷰중"* ]]; then
            echo "Comment contains '리뷰중'. Blocking merge."
            exit 1
          fi
        shell: bash

      - name: Set status check
        if: failure()
        run: echo "Merge blocked due to '리뷰중' keyword in comment." && exit 1